// JSP-CPC Phase 6 — Mode 1 shift/mask UNIT TEST (host-side, plan §4/§8/§10).
//
// The CPC plan flags (twice) that the derived per-mode shift masks "MUST be
// unit-tested against the asset converter's exact byte format before the
// kernels are trusted".  This is that test for Mode 1.
//
// Mode 1 is 4 px/byte with the two bit-planes interleaved across the byte:
// pixel p (0 = leftmost) has its plane-0 bit at position (7-p) (high nibble)
// and its plane-1 bit at position (3-p) (low nibble); the pixel value is
// (plane1<<1)|plane0.  A sprite shifted right by `i` pixels (1..3) is built
// from a per-phase rotation table (jsp_rottbl, generated by jsp_init_rottbl()
// in lib/jsp_init.c, whose entry formula is shared verbatim via
// include/jsp_rottbl_formula.h).  For each source byte the table holds an
// "in-byte" half and a "carry" half, and the compositor combines THIS column's
// in-byte with the LEFT column's carry:
//
//     out_byte = rottbl_in[ this_byte ] | rottbl_carry[ left_byte ]
//
// We verify, with an INDEPENDENT pixel-array reference (decode -> shift the
// 8-pixel window -> re-encode), that:
//   [1] the table halves match a per-pixel right shift of the byte in isolation;
//   [2] the combine equals a true 1-px-per-step shift of the (left|this) window,
//       exhaustively over all byte pairs and phases;
//   [3] (optional) the table behaves over the ACTUAL emitted asset byte values.
// Pure host C (cc), no emulator — runs as a build-time gate.
//
// Build/run:  make cpc-shift-test-mode1
// (usage:  shift_test_mode1 [path/to/mode1_asset.asm])

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

// Select the Mode-1 IN/CARRY split from the shared production formula header —
// the SAME expression jsp_init_rottbl() compiles into the engine.  CPC_MODE1 is
// defined on the command line by the Makefile target.
#include "jsp_rottbl_formula.h"

#define PHASES 3                // Mode 1: shift phases 1..3

static uint8_t rottbl_in[PHASES][256];
static uint8_t rottbl_carry[PHASES][256];

// Build the table from the shared production formula, exactly as
// jsp_init_rottbl() does — no private copy.
static void build_rottbl(void) {
    for (int i = 1; i <= PHASES; i++) {
        for (int val = 0; val <= 255; val++) {
            rottbl_in[i-1][val]    = (uint8_t)JSP_ROTTBL_IN(val, i);
            rottbl_carry[i-1][val] = (uint8_t)JSP_ROTTBL_CARRY(val, i);
        }
    }
}

// ---- Independent Mode-1 pixel reference (NOT using the formula header) ------

// pixel p (0 = leftmost) of a Mode-1 byte
static int m1_get(uint8_t b, int p) {
    int plane0 = (b >> (7 - p)) & 1;
    int plane1 = (b >> (3 - p)) & 1;
    return (plane1 << 1) | plane0;
}
static uint8_t m1_set(uint8_t b, int p, int px) {
    if (px & 1) b |= (uint8_t)(1 << (7 - p));
    if (px & 2) b |= (uint8_t)(1 << (3 - p));
    return b;
}

// Reference in/carry of `v` shifted right by i: window = [v's 4px | 0 0 0 0],
// shift right i, encode positions 0..3 (in-byte) and 4..7 (carry).
static void ref_in_carry(uint8_t v, int i, uint8_t *in, uint8_t *carry) {
    int W[8] = {0,0,0,0,0,0,0,0};
    for (int p = 0; p < 4; p++) W[p] = m1_get(v, p);
    int T[8] = {0,0,0,0,0,0,0,0};
    for (int k = 0; k < 8; k++) T[k] = (k >= i) ? W[k - i] : 0;
    uint8_t bi = 0, bc = 0;
    for (int p = 0; p < 4; p++) { bi = m1_set(bi, p, T[p]); bc = m1_set(bc, p, T[4 + p]); }
    *in = bi; *carry = bc;
}

// Reference screen byte at `this`'s position when the (left|this) window is
// shifted right by i pixels: window pixels [left 4px | this 4px], shift right i,
// encode positions 4..7 (this byte's screen slot).
static uint8_t ref_combine(uint8_t left, uint8_t cur, int i) {
    int W[8];
    for (int p = 0; p < 4; p++) W[p]     = m1_get(left, p);
    for (int p = 0; p < 4; p++) W[4 + p] = m1_get(cur,  p);
    uint8_t out = 0;
    for (int p = 0; p < 4; p++) {
        int src = (4 + p) - i;
        out = m1_set(out, p, (src >= 0) ? W[src] : 0);
    }
    return out;
}

static int fail_count = 0;

#define CHECK(cond, ...) do { if (!(cond)) { \
    if (fail_count < 20) { printf("  FAIL: "); printf(__VA_ARGS__); printf("\n"); } \
    fail_count++; } } while (0)

// [1] table halves match the per-pixel in/carry reference.
static void test_table_vs_reference(void) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int v = 0; v <= 255; v++) {
            uint8_t exp_in, exp_carry;
            ref_in_carry((uint8_t)v, i, &exp_in, &exp_carry);
            CHECK(rottbl_in[i-1][v] == exp_in,
                  "in[i=%d][v=%02X] = %02X, expected %02X", i, v, rottbl_in[i-1][v], exp_in);
            CHECK(rottbl_carry[i-1][v] == exp_carry,
                  "carry[i=%d][v=%02X] = %02X, expected %02X", i, v, rottbl_carry[i-1][v], exp_carry);
            checks += 2;
        }
    }
    printf("[1] table vs per-pixel reference: %d checks\n", checks);
}

// [2] exhaustive combine == true 1-px-per-step window shift.
static void test_combine_exhaustive(void) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int left = 0; left <= 255; left++) {
            for (int cur = 0; cur <= 255; cur++) {
                uint8_t engine = (uint8_t)(rottbl_in[i-1][cur] | rottbl_carry[i-1][left]);
                uint8_t ref    = ref_combine((uint8_t)left, (uint8_t)cur, i);
                CHECK(engine == ref,
                      "combine i=%d left=%02X cur=%02X -> %02X, ref %02X", i, left, cur, engine, ref);
                checks++;
            }
        }
    }
    printf("[2] exhaustive combine vs window shift (256x256x%d): %d checks\n", PHASES, checks);
}

// [3] exercise the table over the ACTUAL emitted asset byte values (sanity
//     tie-back; [2] already covers every possible (left,this) pair).
static void test_emitted_bytes(const uint8_t *bytes, int n) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int k = 0; k < n; k++) {
            uint8_t left = (k == 0) ? 0 : bytes[k-1];
            uint8_t cur  = bytes[k];
            uint8_t engine = (uint8_t)(rottbl_in[i-1][cur] | rottbl_carry[i-1][left]);
            uint8_t ref    = ref_combine(left, cur, i);
            CHECK(engine == ref,
                  "emitted i=%d k=%d left=%02X cur=%02X -> %02X ref %02X", i, k, left, cur, engine, ref);
            checks++;
        }
    }
    printf("[3] emitted asset bytes (%d bytes x %d phases): %d checks\n", n, PHASES, checks);
}

// Parse "db $XX,$YY,..." lines (strip ';' comments) into a flat byte array.
static int load_asm_bytes(const char *path, uint8_t *out, int max) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    char line[512];
    int n = 0;
    while (fgets(line, sizeof line, f)) {
        char *semi = strchr(line, ';'); if (semi) *semi = 0;
        char *p = line;
        while (isspace((unsigned char)*p)) p++;
        if (strncmp(p, "db", 2) != 0) continue;
        p += 2;
        for (char *q = p; *q; q++) {
            if (*q == '$') {
                unsigned v;
                if (sscanf(q + 1, "%x", &v) == 1 && n < max) out[n++] = (uint8_t)v;
            }
        }
    }
    fclose(f);
    return n;
}

int main(int argc, char **argv) {
    printf("JSP-CPC Mode 1 shift/mask unit test\n");
    build_rottbl();

    test_table_vs_reference();
    test_combine_exhaustive();

    // The emitted-asset cross-check runs only when an asset path is given (the
    // Mode-1 emitter may not exist yet); the core math gate is [1]/[2].
    if (argc > 1) {
        static uint8_t bytes[8192];
        int n = load_asm_bytes(argv[1], bytes, sizeof bytes);
        if (n < 2) {
            printf("[3] emitted asset bytes: FAIL — read %d bytes from %s (need >=2)\n", n, argv[1]);
            printf("RESULT: FAIL (asset not loaded)\n");
            return 1;
        }
        test_emitted_bytes(bytes, n);
    } else {
        printf("[3] emitted asset bytes: skipped (no asset path given)\n");
    }

    if (fail_count == 0) {
        printf("RESULT: PASS\n");
        return 0;
    }
    printf("RESULT: FAIL (%d mismatches)\n", fail_count);
    return 1;
}
