// JSP-CPC Phase 4 — Mode 2 shift/mask UNIT TEST (host-side, plan §4/§8/§10).
//
// The CPC plan flags (twice) that the derived per-mode shift masks "MUST be
// unit-tested against the asset converter's exact byte format before the
// kernels are trusted".  This is that test for Mode 2.
//
// Mode 2 is 1bpp-linear (8 px/byte), identical to the ZX format, so the CPC
// Mode-2 sprite asset IS the ZX 1bpp mask2/load1 byte format (mask,graph pairs
// for mask2; graph only for load1) — see tests/test_sprite_mask2.asm.  A sprite
// shifted right by `i` pixels (1..7) is built from a per-phase rotation table
// (jsp_rottbl, generated by jsp_init_rottbl() in lib/jsp_init.c): for each
// source byte the table holds an "in-byte" half and a "carry" half, and the
// compositor combines this column's in-byte with the LEFT column's carry:
//
//     out_byte = rottbl_in[ this_byte ] | rottbl_carry[ left_byte ]
//
// This must equal a true 16-bit right shift of the (left<<8 | this) window.
// We verify that, exhaustively over all byte pairs and over the actual emitted
// asset bytes.  Pure host C (cc), no emulator — runs as a build-time gate.
//
// Build/run:  make cpc-shift-test-mode2
// (usage:  shift_test_mode2 [path/to/test_sprite_mask2.asm])

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

// The rottbl entry formula is shared verbatim with the production generator
// jsp_init_rottbl() (lib/jsp_init.c) via this header — so build_rottbl() below
// builds the table from the SAME expression the engine uses, and tests [2]/[3]
// (the independent 16-bit-shift checks) therefore validate the production
// formula, not a private copy that could drift.
#include "jsp_rottbl_formula.h"

#define PHASES 7                // Mode 2: shift phases 1..7

// rottbl_in[i-1][v] / rottbl_carry[i-1][v] for shift i, source byte v.
static uint8_t rottbl_in[PHASES][256];
static uint8_t rottbl_carry[PHASES][256];

// Build the table from the shared production formula (jsp_rottbl_formula.h),
// exactly as jsp_init_rottbl() does — no private copy.
static void build_rottbl(void) {
    for (int i = 1; i <= PHASES; i++) {
        for (int val = 0; val <= 255; val++) {
            rottbl_in[i-1][val]    = (uint8_t)JSP_ROTTBL_IN(val, i);
            rottbl_carry[i-1][val] = (uint8_t)JSP_ROTTBL_CARRY(val, i);
        }
    }
}

static int fail_count = 0;

#define CHECK(cond, ...) do { if (!(cond)) { \
    if (fail_count < 20) { printf("  FAIL: "); printf(__VA_ARGS__); printf("\n"); } \
    fail_count++; } } while (0)

// 1) The shared production formula matches the §8.1 closed form
//    in = v>>i, carry = (v<<(8-i))&0xFF.  This locks the closed form as the
//    Mode-2 spec; the real shift correctness is proved by tests [2]/[3].
static void test_table_closed_form(void) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int v = 0; v <= 255; v++) {
            uint8_t exp_in    = (uint8_t)(v >> i);
            uint8_t exp_carry = (uint8_t)((v << (8 - i)) & 0xFF);
            CHECK(rottbl_in[i-1][v] == exp_in,
                  "in[i=%d][v=%02X] = %02X, expected %02X", i, v, rottbl_in[i-1][v], exp_in);
            CHECK(rottbl_carry[i-1][v] == exp_carry,
                  "carry[i=%d][v=%02X] = %02X, expected %02X", i, v, rottbl_carry[i-1][v], exp_carry);
            checks += 2;
        }
    }
    printf("[1] table closed-form (in=v>>i, carry=(v<<(8-i))&0xFF): %d checks\n", checks);
}

// 2) Exhaustive combine == true 16-bit shift: for every (left,this) byte pair
//    and every phase, out = in[this] | carry[left]  must equal
//    (((left<<8)|this) >> i) & 0xFF.
static void test_combine_exhaustive(void) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int left = 0; left <= 255; left++) {
            for (int cur = 0; cur <= 255; cur++) {
                uint8_t engine = (uint8_t)(rottbl_in[i-1][cur] | rottbl_carry[i-1][left]);
                uint8_t ref    = (uint8_t)((((left << 8) | cur) >> i) & 0xFF);
                CHECK(engine == ref,
                      "combine i=%d left=%02X cur=%02X -> %02X, ref %02X", i, left, cur, engine, ref);
                checks++;
            }
        }
    }
    printf("[2] exhaustive combine vs 16-bit shift (256x256x%d): %d checks\n", PHASES, checks);
}

// 3) Exercise the table over the ACTUAL emitted asset byte VALUES (the
//    converter's exact output).  Note: this pairs each byte with its
//    file-adjacent predecessor, which is NOT the kernel's true left-column
//    neighbour (mask/graph are interleaved, columns-major) — so this is the
//    exhaustive check [2] re-run on the real byte values as a sanity tie-back,
//    not a structural validation of the column layout.  [2] already covers
//    every possible (left,this) pair, including all real column adjacencies.
static void test_emitted_bytes(const uint8_t *bytes, int n) {
    int checks = 0;
    for (int i = 1; i <= PHASES; i++) {
        for (int k = 0; k < n; k++) {
            uint8_t left = (k == 0) ? 0 : bytes[k-1];
            uint8_t cur  = bytes[k];
            uint8_t engine = (uint8_t)(rottbl_in[i-1][cur] | rottbl_carry[i-1][left]);
            uint8_t ref    = (uint8_t)((((left << 8) | cur) >> i) & 0xFF);
            CHECK(engine == ref,
                  "emitted i=%d k=%d left=%02X cur=%02X -> %02X ref %02X", i, k, left, cur, engine, ref);
            checks++;
        }
    }
    printf("[3] emitted asset bytes (%d bytes x %d phases): %d checks\n", n, PHASES, checks);
}

// Parse "db $XX,$YY,..." lines (strip ';' comments) into a flat byte array.
static int load_asm_bytes(const char *path, uint8_t *out, int max) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    char line[512];
    int n = 0;
    while (fgets(line, sizeof line, f)) {
        char *semi = strchr(line, ';'); if (semi) *semi = 0;
        char *p = line;
        while (isspace((unsigned char)*p)) p++;
        if (strncmp(p, "db", 2) != 0) continue;     // only data lines
        p += 2;
        for (char *q = p; *q; q++) {
            if (*q == '$') {
                unsigned v;
                if (sscanf(q + 1, "%x", &v) == 1 && n < max) out[n++] = (uint8_t)v;
            }
        }
    }
    fclose(f);
    return n;
}

int main(int argc, char **argv) {
    const char *asmpath = (argc > 1) ? argv[1] : "tests/test_sprite_mask2.asm";

    printf("JSP-CPC Mode 2 shift/mask unit test\n");
    build_rottbl();

    test_table_closed_form();
    test_combine_exhaustive();

    static uint8_t bytes[8192];
    int n = load_asm_bytes(asmpath, bytes, sizeof bytes);
    if (n < 2) {
        // Hard failure, not a silent skip: the Makefile always passes the asset,
        // so an unreadable / near-empty file means the gate is not running.
        printf("[3] emitted asset bytes: FAIL — read %d bytes from %s (need >=2)\n", n, asmpath);
        printf("RESULT: FAIL (asset not loaded)\n");
        return 1;
    }
    test_emitted_bytes(bytes, n);

    if (fail_count == 0) {
        printf("RESULT: PASS\n");
        return 0;
    }
    printf("RESULT: FAIL (%d mismatches)\n", fail_count);
    return 1;
}
