#!/usr/bin/env perl
#
# gfxgen.pl — unified JSP sprite/tile asset emitter.
#
# Selects the per-platform code path with --platform:
#   --platform zx    ZX Spectrum 1bpp (mask2 / load1 sprites, tiles, C or ASM)
#   --platform cpc   Amstrad CPC Mode 0/1 planar (sprite_mask/load/imask, tiles,
#                    --multicolor, --palette-symbol)
#
# All other options are passed through unchanged to the selected platform
# module (tools/lib/JSPGfx/{ZX,CPC}.pm), so the per-platform option set and the
# generated bytes are exactly what the former standalone gfxgen.pl / cpcgfx.pl
# produced.  Run with a platform and no further args for that platform's usage.

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";	# vendored ZXGfx.pm + JSPGfx/*.pm — JSP self-contained

use Getopt::Long;

sub usage {
    my $msg = shift;
    print STDERR "$msg\n\n" if $msg;
    print STDERR <<"EOF_USAGE";
gfxgen.pl --platform <zx|cpc> [platform-specific options...]

  --platform zx     ZX Spectrum 1bpp asset emitter
  --platform cpc    Amstrad CPC Mode 0/1 asset emitter

Run with a platform selected and no further arguments to see that
platform's full option list.
EOF_USAGE
    exit 1;
}

# Pull --platform off the front, leave every other argument in @ARGV for the
# platform module to parse with its own (unchanged) option grammar.
my $platform;
Getopt::Long::Configure( "pass_through", "no_auto_abbrev", "no_bundling" );
GetOptions( 'platform=s' => \$platform ) or usage();
defined $platform or usage( "--platform is required" );
$platform = lc $platform;

if ( $platform eq 'zx' ) {
    require JSPGfx::ZX;
    JSPGfx::ZX::run( @ARGV );
} elsif ( $platform eq 'cpc' ) {
    require JSPGfx::CPC;
    JSPGfx::CPC::run( @ARGV );
} else {
    usage( "--platform must be 'zx' or 'cpc' (got '$platform')" );
}
